# Imagem base com PHP 7.4 e Apache
FROM php:7.4-apache

# Definindo o diretório de trabalho
WORKDIR /var/www/html

# Copiando os arquivos necessários para o diretório de trabalho
COPY index.php conexao.php ./

# Instalando dependências e extensões do PHP
RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
    && docker-php-ext-configure gd \
        --with-freetype=/usr/include/ \
        --with-jpeg=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd pdo_mysql mysqli

# Expondo a porta 80
EXPOSE 80
